/* Auto-generated by scripts/generate-typography-styles.ts */
/* Override Radix variables */
.radix-themes {
  --default-font-family: Inter, "Inter Fallback", Arial;
  --heading-font-family: Inter, "Inter Fallback", Arial;
  --font-size-1: 13.75px;
  --line-height-1: 16px;
  --font-size-2: 16.5px;
  --line-height-2: 20px;
  --font-size-3: 19.25px;
  --line-height-3: 24px;
  --font-size-4: 22px;
  --line-height-4: 26px;
  --font-size-5: 24.75px;
  --line-height-5: 26px;
  --font-size-6: 27.5px;
  --line-height-6: 28px;
  --font-size-7: 33px;
  --line-height-7: 32px;
  --font-size-8: 48.125px;
  --line-height-8: 40px;
  --font-size-9: 82.5px;
  --line-height-9: 60px;
}

/* Default text styles */

.rt-Text {
  font-size: 19.25px;
  line-height: 24px;
}

.rt-Text::before {
  content: "";
  margin-bottom: -0.2597em;
  display: table;
}

.rt-Text::after {
  content: "";
  margin-top: -0.2597em;
  display: table;
}

/* Class names for text elements */

.rt-r-size-1:not(.rt-DialogContent) {
  font-size: 13.75px;
  line-height: 16px;
}

.rt-r-size-1:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.2182em;
  display: table;
}

.rt-r-size-1:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.2182em;
  display: table;
}

.rt-r-size-2:not(.rt-DialogContent) {
  font-size: 16.5px;
  line-height: 20px;
}

.rt-r-size-2:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.2424em;
  display: table;
}

.rt-r-size-2:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.2424em;
  display: table;
}

.rt-r-size-3:not(.rt-DialogContent) {
  font-size: 19.25px;
  line-height: 24px;
}

.rt-r-size-3:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.2597em;
  display: table;
}

.rt-r-size-3:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.2597em;
  display: table;
}

.rt-r-size-4:not(.rt-DialogContent) {
  font-size: 22px;
  line-height: 26px;
}

.rt-r-size-4:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.2273em;
  display: table;
}

.rt-r-size-4:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.2273em;
  display: table;
}

.rt-r-size-5:not(.rt-DialogContent) {
  font-size: 24.75px;
  line-height: 26px;
}

.rt-r-size-5:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.1616em;
  display: table;
}

.rt-r-size-5:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.1616em;
  display: table;
}

.rt-r-size-6:not(.rt-DialogContent) {
  font-size: 27.5px;
  line-height: 28px;
}

.rt-r-size-6:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.1455em;
  display: table;
}

.rt-r-size-6:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.1455em;
  display: table;
}

.rt-r-size-7:not(.rt-DialogContent) {
  font-size: 33px;
  line-height: 32px;
}

.rt-r-size-7:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.1212em;
  display: table;
}

.rt-r-size-7:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.1212em;
  display: table;
}

.rt-r-size-8:not(.rt-DialogContent) {
  font-size: 48.125px;
  line-height: 40px;
}

.rt-r-size-8:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: -0.0519em;
  display: table;
}

.rt-r-size-8:not(.rt-DialogContent)::after {
  content: "";
  margin-top: -0.0519em;
  display: table;
}

.rt-r-size-9:not(.rt-DialogContent) {
  font-size: 82.5px;
  line-height: 60px;
}

.rt-r-size-9:not(.rt-DialogContent)::before {
  content: "";
  margin-bottom: 0em;
  display: table;
}

.rt-r-size-9:not(.rt-DialogContent)::after {
  content: "";
  margin-top: 0em;
  display: table;
}
